export const dates = [
  { date: 1 },
  { date: 2 },
  { date: 3 },
  { date: 4 },
  { date: 5 },
  { date: 6 },
  { date: 7 },
  { date: 8 },
  { date: 9 },
  { date: 10 },
  { date: 11 },
  { date: 12 },
  { date: 13 },
  { date: 14 },
  { date: 15 },
  { date: 16 },
  { date: 17 },
  { date: 18 },
  { date: 19 },
  { date: 20 },
  { date: 21 },
  { date: 22 },
  { date: 23 },
  { date: 24 },
  { date: 25 },
  { date: 26 },
  { date: 27 },
  { date: 28 },
  { date: 29 },
  { date: 30 },
  { date: 31 },
];

export const months = [
  { number: 1 , month: "January" },
  { number: 2 , month: "February" },
  { number: 3 , month: "March" },
  { number: 4 , month: "April" },
  { number: 5 , month: "May" },
  { number: 6 , month: "June" },
  { number: 7 , month: "July" },
  { number: 8 , month: "August" },
  { number: 9 , month: "September" },
  { number: 10 , month: "October" },
  { number: 11 , month: "November" },
  { number: 12 , month: "December" },
];
